# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Github\cebiusdaten\DatenDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_datenDialog(object):
    def setupUi(self, datenDialog):
        datenDialog.setObjectName("datenDialog")
        datenDialog.resize(640, 480)
        self.starten = QtWidgets.QPushButton(datenDialog)
        self.starten.setGeometry(QtCore.QRect(540, 440, 89, 28))
        self.starten.setObjectName("starten")
        self.abbrechen = QtWidgets.QPushButton(datenDialog)
        self.abbrechen.setGeometry(QtCore.QRect(440, 440, 89, 28))
        self.abbrechen.setObjectName("abbrechen")
        self.truncateGebref = QtWidgets.QCheckBox(datenDialog)
        self.truncateGebref.setGeometry(QtCore.QRect(50, 20, 371, 21))
        self.truncateGebref.setObjectName("truncateGebref")
        self.truncateKreis = QtWidgets.QCheckBox(datenDialog)
        self.truncateKreis.setGeometry(QtCore.QRect(50, 50, 261, 21))
        self.truncateKreis.setObjectName("truncateKreis")
        self.importGebref = QtWidgets.QCheckBox(datenDialog)
        self.importGebref.setGeometry(QtCore.QRect(50, 100, 321, 21))
        self.importGebref.setObjectName("importGebref")
        self.importKreis = QtWidgets.QCheckBox(datenDialog)
        self.importKreis.setGeometry(QtCore.QRect(50, 130, 201, 21))
        self.importKreis.setObjectName("importKreis")
        self.exportCebius = QtWidgets.QCheckBox(datenDialog)
        self.exportCebius.setGeometry(QtCore.QRect(50, 180, 281, 21))
        self.exportCebius.setObjectName("exportCebius")

        self.retranslateUi(datenDialog)
        self.abbrechen.clicked.connect(datenDialog.abbrechen) # type: ignore
        self.starten.clicked.connect(datenDialog.weiter) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(datenDialog)

    def retranslateUi(self, datenDialog):
        _translate = QtCore.QCoreApplication.translate
        datenDialog.setWindowTitle(_translate("datenDialog", "Dialog"))
        self.starten.setText(_translate("datenDialog", "starten"))
        self.abbrechen.setText(_translate("datenDialog", "abbrechen"))
        self.truncateGebref.setText(_translate("datenDialog", "Gebref-Tabellen leeren"))
        self.truncateKreis.setText(_translate("datenDialog", "Kreistabelle leeren"))
        self.importGebref.setText(_translate("datenDialog", "Gebref-Tabellen neu einlesen"))
        self.importKreis.setText(_translate("datenDialog", "Kreistabelle neu einlesen"))
        self.exportCebius.setText(_translate("datenDialog", "Cebiusdateien ausgeben"))
